version: '3'

services:
  cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - ./data/cache:/data:db
    command: ['--requirepass "secret"']
    env_file:
      - .env

  db:
    image: mongo
    container_name: mongodb
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
